// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package imagemodifiertoolbox.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.awt.image.BufferedImage;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.Graphics2D;
import java.awt.AlphaComposite;
import java.awt.Color;
import com.mendix.core.Core;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import java.awt.image.RescaleOp;

/**
 * Modifies the brightness/contrast of image
 */
public class ImageBrightnessAndContrast extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __OriginalImage;
	private system.proxies.Image OriginalImage;
	private java.math.BigDecimal BrightnessScale;
	private java.math.BigDecimal ContrastOffset;

	public ImageBrightnessAndContrast(IContext context, IMendixObject OriginalImage, java.math.BigDecimal BrightnessScale, java.math.BigDecimal ContrastOffset)
	{
		super(context);
		this.__OriginalImage = OriginalImage;
		this.BrightnessScale = BrightnessScale;
		this.ContrastOffset = ContrastOffset;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.OriginalImage = this.__OriginalImage == null ? null : system.proxies.Image.initialize(getContext(), __OriginalImage);

		// BEGIN USER CODE
		String filename = OriginalImage.getName();
		String extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
		
		// Checks image is in valid format for modification
		if (!extension.equals("png")) {
			Core.getLogger("ImageModifier").error("The file must be a png file.");
		}
		else {	
			if (__OriginalImage == null) {
				throw new NullPointerException("No image provided.");
			} 
			else if (OriginalImage.getHasContents() != true) {
				Core.getLogger("ImageModifier").error("The input image has no contents.");
				return false;
			} 
			else {
				IContext context = this.getContext();

				BufferedImage image = null;
				BufferedImage tintedImage = null;
				InputStream inputStream = null;
				ByteArrayOutputStream outputStream = null;
				
				try {
					
					image = ImageIO.read(Core.getImage(context, __OriginalImage, false));
					
					tintedImage = tintedTransform(image, BrightnessScale.floatValue(), ContrastOffset.floatValue());
					outputStream = new ByteArrayOutputStream();
					ImageIO.write(tintedImage, extension, outputStream);
					inputStream = new ByteArrayInputStream(outputStream.toByteArray());
					// Stores modified image
					Core.storeImageDocumentContent(context, __OriginalImage, inputStream, 100, 100);
					return true;

				} catch (NullPointerException e) {
					Core.getLogger("ImageModifier").error(e.getMessage(), e);
					return false;
				} catch (Exception e) {
					Core.getLogger("ImageModifier").error(e.getMessage(), e);
					return false;
				} finally {
					inputStream.close();
					outputStream.close();
					}
				}
			}
			return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImageBrightnessAndContrast";
	}

	// BEGIN EXTRA CODE
	public BufferedImage tintedTransform(BufferedImage image, float brightnessScale, float contrastOffset) {		
		// Modifies brightness and contrast
		RescaleOp rescaleOp = new RescaleOp(brightnessScale, contrastOffset, null);
		// Source and destination are the same so no need to duplicate image
		rescaleOp.filter(image, image);
		
		return image;
	}
	// END EXTRA CODE
}
