// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package imagemodifiertoolbox.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.awt.image.BufferedImage;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import com.mendix.core.Core;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import java.awt.AlphaComposite;
import java.awt.Color;

/**
 * Change an imgae to grayscale or add a coloured tint
 */
public class ImageChangeColour extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __OriginalImage;
	private system.proxies.Image OriginalImage;
	private imagemodifiertoolbox.proxies.ENUM_ImageColour Colour;

	public ImageChangeColour(IContext context, IMendixObject OriginalImage, java.lang.String Colour)
	{
		super(context);
		this.__OriginalImage = OriginalImage;
		this.Colour = Colour == null ? null : imagemodifiertoolbox.proxies.ENUM_ImageColour.valueOf(Colour);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.OriginalImage = this.__OriginalImage == null ? null : system.proxies.Image.initialize(getContext(), __OriginalImage);

		// BEGIN USER CODE
		String filename = OriginalImage.getName();
		String extension = filename.substring(filename.lastIndexOf(".") + 1, filename.length());
		
		// Checks image is in valid format for modification
		if (!extension.equals("png")) {
			Core.getLogger("ImageModifier").error("The file must be a png file.");
		}
		else {	
			if (__OriginalImage == null) {
				throw new NullPointerException("No image provided.");
			} 
			else if (OriginalImage.getHasContents() != true) {
				Core.getLogger("ImageModifier").error("The input image has no contents.");
				return false;
			} 
			else {
				IContext context = this.getContext();

				BufferedImage image = null;
				BufferedImage colouredImage = null;
				InputStream inputStream = null;
				ByteArrayOutputStream outputStream = null;
				
				try {

					image = ImageIO.read(Core.getImage(context, __OriginalImage, false));
					
					// If no colour given, assume no filter wanted
					String colourString = (Colour != null) ? Colour.name().toLowerCase() : "default";
					
					colouredImage = colourTransform(image, colourString);
					
					outputStream = new ByteArrayOutputStream();
					ImageIO.write(colouredImage, extension, outputStream);
					inputStream = new ByteArrayInputStream(outputStream.toByteArray());
					// Stores modified image
					Core.storeImageDocumentContent(context, __OriginalImage, inputStream, 100, 100);
					return true;

				} catch (NullPointerException e) {
					Core.getLogger("ImageModifier").error(e.getMessage(), e);
					return false;
				} catch (Exception e) {
					Core.getLogger("ImageModifier").error(e.getMessage(), e);
					return false;
				} finally {
					inputStream.close();
					outputStream.close();
					}
				}
			}
			return true;
		
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImageChangeColour";
	}

	// BEGIN EXTRA CODE
	public BufferedImage colourTransform(BufferedImage image, String colourLowerCase) {	
		int colourType = BufferedImage.TYPE_INT_ARGB; // Default style
		Color applyTint = Color.RED;
		
		switch (colourLowerCase) {
			case "grayscale":
				colourType = BufferedImage.TYPE_BYTE_GRAY; // grayscale
				break;
			case "red":
				applyTint = Color.RED;
				break;
			case "blue":
				applyTint = Color.BLUE;
				break;
			case "green":
				applyTint = Color.GREEN;
				break;
		}
		
		BufferedImage colouredImage = new BufferedImage(image.getWidth(), image.getHeight(), colourType);  
		Graphics2D g = colouredImage.createGraphics();
		g.drawImage(image, 0, 0, image.getWidth(), image.getHeight(), null); 
		if (colourLowerCase.equals("red") || colourLowerCase.equals("blue") || colourLowerCase.equals("green")) {
			g.setComposite(AlphaComposite.SrcAtop.derive(0.3f));
			g.setColor(applyTint);
			g.fillRect(0, 0, image.getWidth(), image.getHeight());
		}
		g.dispose(); 
			
		return colouredImage;
	}
	
	
	
	// END EXTRA CODE
}
